name: CI

on:
- push

jobs:
  e2e_tests:
    name: end to end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup phpipam
        uses: codeaffen/phpipam-action@v1
      - name: prepare tests
        run: |
          make test-setup
        env:
          PHPIPAM_URL: "https://localhost"
          PHPIPAM_APPID: "ansible"
          PHPIPAM_USERNAME: "admin"
          PHPIPAM_PASSWORD: "ipamadmin"
          PHPIPAM_VALIDATE_CERTS: False
      - name: run all tests
        run: |
          make test-all
        env:
          PYTHONWARNINGS: "ignore:Unverified HTTPS request"
          PHPIPAM_VALIDATE_CERTS: False
